# Generated by Django 5.1.4 on 2026-05-21 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "immatriculation",
                    models.CharField(
                        help_text="Numéro d'immatriculation unique du bus (ex: DK-1234-AB).",
                        max_length=20,
                        unique=True,
                        verbose_name="Immatriculation",
                    ),
                ),
                (
                    "nombre_places",
                    models.PositiveIntegerField(
                        help_text="Capacité totale du bus (minimum 1 place).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Nombre de places",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("INACTIF", "Inactif"),
                            ("MAINTENANCE", "En maintenance"),
                        ],
                        default="ACTIF",
                        help_text="État actuel du bus. Seuls les bus ACTIFS peuvent être assignés à des trajets.",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Remarques internes sur ce bus (optionnel).",
                        verbose_name="Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus",
                "verbose_name_plural": "Bus",
                "ordering": ["immatriculation"],
            },
        ),
    ]
