# Generated by Django 5.1.4 on 2026-05-21 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trajets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_places",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de places à réserver (minimum 1).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Nombre de places",
                    ),
                ),
                (
                    "date_reservation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de réservation"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRMEE", "Confirmée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_ATTENTE",
                        help_text="État actuel de la réservation.",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Commentaires ou raison d'annulation (optionnel).",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Utilisateur qui effectue la réservation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        help_text="Le trajet pour lequel la réservation est faite.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="trajets.trajet",
                        verbose_name="Trajet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-date_reservation"],
            },
        ),
    ]
