# Generated by Django 5.1.4 on 2026-05-21 12:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trajet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ville_depart",
                    models.CharField(
                        help_text="Nom de la ville ou localité de départ.",
                        max_length=100,
                        verbose_name="Ville de départ",
                    ),
                ),
                (
                    "ville_arrivee",
                    models.CharField(
                        help_text="Nom de la ville ou localité d'arrivée.",
                        max_length=100,
                        verbose_name="Ville d'arrivée",
                    ),
                ),
                (
                    "date_depart",
                    models.DateField(
                        help_text="Date prévue du départ (format: JJ/MM/AAAA).",
                        verbose_name="Date de départ",
                    ),
                ),
                (
                    "heure_depart",
                    models.TimeField(
                        help_text="Heure prévue du départ (format: HH:MM).",
                        verbose_name="Heure de départ",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix d'une place en FCFA. Minimum 0,01.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Prix (par place)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        help_text="Sélectionnez un bus ACTIF pour ce trajet.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trajets",
                        to="bus.bus",
                        verbose_name="Bus assigné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trajet",
                "verbose_name_plural": "Trajets",
                "ordering": ["-date_depart", "heure_depart"],
                "unique_together": {("bus", "date_depart", "heure_depart")},
            },
        ),
    ]
